services:
  price_tracker:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8085:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: on-failure