services:
  price_tracker:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: on-failure
    networks:
      - app_network

networks:
  app_network:
    driver: bridge